# Generated by Django 4.2.5 on 2024-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='url',
        ),
        migrations.AddField(
            model_name='film',
            name='film_file',
            field=models.FileField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AddField(
            model_name='film',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
