# Generated by Django 5.0.1 on 2024-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_topic_alter_admin_id_alter_film_id_film_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='topics',
            field=models.ManyToManyField(related_name='Film', to='films.topic'),
        ),
    ]
