# Generated by Django 5.0.1 on 2024-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='topics',
            field=models.ManyToManyField(related_name='films', to='films.topic'),
        ),
    ]
