# Generated by Django 5.0.1 on 2024-09-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='topics',
            new_name='genres',
        ),
    ]
